server:
  port: 8080
  host: "0.0.0.0"

mongodb:
  uri: "mongodb://mongodb:27017"
  database: "meddoc"

log:
  level: "info"
  format: "json"

auth:
  secret: "BqJSM9iEneFFsSKumGIUGgpGzN13t6gIeJYhE6392AI="
  access_token_ttl: "15m"
  refresh_token_ttl: "720h"