services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      target: app
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 