openapi: 3.0.0
info:
  title: MedDoc API
  version: 1.0.0
  description: API for managing medical documents

servers:
  - url: /api/v1
    description: API v1

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '401':
          description: Invalid credentials
        '400':
          description: Invalid input

  /auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshToken'
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '401':
          description: Invalid refresh token
        '400':
          description: Invalid input

  /documents:
    get:
      summary: Get all user documents
      description: Returns a list of all documents belonging to the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
    post:
      summary: Create a new document
      description: Creates a new document for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentCreation'
      responses:
        '201':
          description: Document created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /documents/{id}:
    get:
      summary: Get document by ID
      description: Returns a document by its ID. The document must belong to the authenticated user.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: Document ID
          example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Document details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '401':
          description: Unauthorized
        '403':
          description: Access denied (trying to access another user's document)
        '404':
          description: Document not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
    patch:
      summary: Update document by ID
      description: Updates a document by its ID. The document must belong to the authenticated user.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: Document ID
          example: "507f1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentUpdate'
      responses:
        '200':
          description: Document updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Access denied (trying to access another user's document)
        '404':
          description: Document not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
    delete:
      summary: Delete document by ID
      description: Deletes a document by its ID. The document must belong to the authenticated user.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: Document ID
          example: "507f1f77bcf86cd799439011"
      responses:
        '204':
          description: Document deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Access denied (trying to access another user's document)
        '404':
          description: Document not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /files/upload:
    post:
      summary: Upload a file
      description: |
        Upload a file to the system. Files smaller than 1MB are stored locally,
        larger files are stored in GridFS. Returns a file ID that can be used to download the file.
        Allowed file types: PDF, JPEG, JPG, PNG. Maximum file size: 100MB.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: File to upload (max size 100MB)
                metadata:
                  type: object
                  description: Optional file metadata
                  properties:
                    name:
                      type: string
                      description: Original filename
                    type:
                      type: string
                      description: MIME type of the file
                    size:
                      type: integer
                      description: File size in bytes
      responses:
        '201':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier of the uploaded file
                required:
                  - id
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum: 
                      - file too large
                      - invalid file type
                      - missing file
                      - invalid metadata
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /files/{id}:
    get:
      summary: Download a file
      description: |
        Download a file by its ID. The file must belong to the authenticated user.
        Returns the file content with appropriate Content-Type and Content-Disposition headers.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: File ID
          example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: File content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          headers:
            Content-Type:
              schema:
                type: string
                enum: [application/pdf, image/jpeg, image/jpg, image/png, application/octet-stream]
              description: MIME type of the file
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="document.pdf"
              description: Filename for download
            Content-Length:
              schema:
                type: integer
              description: Size of the file in bytes
        '401':
          description: Unauthorized
        '403':
          description: Access denied (trying to access another user's file)
        '404':
          description: File not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        file:
          type: string
        category:
          type: string
        priority:
          type: integer
        content:
          type: object
          additionalProperties:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - title

    DocumentCreation:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        file:
          type: string
        category:
          type: string
        priority:
          type: integer
        content:
          type: object
          additionalProperties:
            type: string
      required:
        - title

    DocumentUpdate:
      type: object
      properties:
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        file:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        priority:
          type: integer
          nullable: true
        content:
          type: object
          additionalProperties:
            type: string

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - email
        
    UserRegistration:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
        name:
          type: string
      required:
        - email
        - password

    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    TokenPair:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
          description: Access token expiration time in seconds
      required:
        - access_token
        - refresh_token
        - expires_in

    RefreshToken:
      type: object
      properties:
        refresh_token:
          type: string
      required:
        - refresh_token 